### PR TITLE
Added artist + album commands

### PR DESCRIPTION
**Pull request by jac0b-w**
Added artist + album commands
Added playlist-read-collaborative scope
Removed duplicate methods

### CODE REVIEW

**Comment by petergmurphy** [comment]
Hi Jacob, could you please update your fork from the master and update the code in it to follow how interactions.py now works. The UML diagram for it is [here](https://github.com/spotlightify/spotlightify/tree/master/spotlight/manager), please follow this diagram when implementing your code. Thanks.

**Comment by jac0b-w** [comment]
@petergmurphy Sure

**Comment by jac0b-w** [comment]
I had to clear my cache to get it work

**Comment by petergmurphy** [comment]
Code runs well and works effectively, merging now, thanks

**Pull request merged**
