### PR TITLE
Creation of Preferences.py

### PR DESCRIPTION
**Pull request by MarkMcMoran**
Modifications made for this PR...

auth/Preferences.py 
Functions created: 
themeConfig - This is a placeholder theming function, can be removed if no longer needed...
runPreChecks - This deals with the possibility of there being no config.json file present...

Reason why these were made? 
To centralise and make the project settings more maintable..

Removal of _config.py & .editorconfig 
This is deprecated as it serves its purpose in the earlier stages of the project (before OOP set up of config.py)
.editorconfig does not belong in a public project (or any) as everyone has their own editor configurations...

app.py

Function created:
uiInvoke:

This is the try catch statement that was utilised in the run function.

Please provide feedback, and what I should include / remove.

Many thanks,

Mark

### CODE REVIEW

**Comment by petergmurphy** [comment]
Hi Mark,

I've found a bug that restricts users from using the application after starting it for the first time.

This bug can be replicated by deleting (or moving) the "cache" folder and running then application. After the user fills their details in and saves, the authentication window reopens instead of letting the user access the application. Please fix this bug.

The method names need changed so that they follow Pythonic method naming conventions. Methods should all be in lower case and must use '_' instead of a change in case. e.g. `runPreChecks` should be `run_pre_checks`.

The preferences class should be made into a singleton class which stores user and settings information such as username, theme and any other variables you deem reasonable to add.

Many thanks,
Peter

**Comment by MarkMcMoran** [comment]
Double commit is a WIP.. I'm still looking into the bug issue however... It's likely correlated to the splitting of the old run func.. I'll see if I can get a work around in place.... I'll keep you posted on this @petergmurphy

**Comment by MarkMcMoran** [comment]
Hi @petergmurphy, 

It seems that I have resolved this issue.. I deleted the config.json, and it no longer appears to "hang". 
To resolve this issue I modified the following in the Preferences.py file:

```   app.setQuitOnLastWindowClosed(True) ``` to ``` app.setQuitOnLastWindowClosed(False)````

This was more than likely due to the fact of this code existing on a separate py file as it worked fine when it was under the run function in the old iteration of the file.

Please test, and let me know if it works fine for you too.


Thanks

**Comment by MarkMcMoran** [comment]
Resolved bug, however once the config.json is created it will stop the app. You have to re-start the app to start using this...

**Pull request merged**
